### ISSUE TITLE
Convert to @eslint/markdown

### ISSUE THREAD

**Issue by nzakas** [eslint/markdown#260]
As part of our [language plugins](https://eslint.org/blog/2024/07/whats-coming-next-for-eslint/) work, this package will be renamed to `@eslint/markdown` over a series of PRs:

- [x] https://github.com/eslint/eslint-plugin-markdown/pull/258
- [x] https://github.com/eslint/eslint-plugin-markdown/pull/259
- [x] https://github.com/eslint/eslint-plugin-markdown/issues/255
- [x] Rename to `@eslint/markdown`
- [x] Rename repo to `eslint/markdown`
- [x] Create markdown language
- [x] Publish to JSR

**Comment by pauliesnug** [comment]
The README.md has been updated to use `npm install @eslint/markdown`, but the NPM package hasn't been published yet

**Comment by nzakas** [comment]
All done! :tada:
