### ISSUE TITLE
`tsx`  code block support

### ISSUE THREAD

**Issue by tianyingchun** [eslint/markdown#269]
<img width="475" alt="image" src="https://github.com/user-attachments/assets/5cbc78e4-7447-4d62-983c-9fd23394458e">

<img width="473" alt="image" src="https://github.com/user-attachments/assets/52b13978-eeba-4e5f-aa93-a05d67e65504">

jsx works fine. can we allow `tsx` support aslo?

**Comment by nzakas** [comment]
The error isn't coming from this plugin. It's coming from whatever you've configured to lint `*.tsx` files.
