### ISSUE TITLE
Docs: README: wrong rule description, missing recommended list

### ISSUE THREAD

**Issue by danielrentz** [eslint/markdown#273]
### Docs page(s)

https://github.com/eslint/markdown/blob/main/README.md

### What documentation issue do you want to solve?

1. Rule table: "no-html" contains wrong description "Enforce fenced code blocks to specify a language."
2. There is no information which rules are included in "recommended".

### What do you think is the correct solution?

1. Rule table: "no-html" description should be "Disallow HTML tags.".
2. The rule table should contain a "Recommended" column.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Yeah, just a copy-paste error. Updating the README automatically would be nice! Feel free to put that together.

**Comment by fasttime** [comment]
I'll work on this.
