### ISSUE TITLE
New Rule: rules regarding actual content

### ISSUE THREAD

**Issue by ghost** [eslint/markdown#288]
### Rule details

I am missing out a whole category of rules that are also not for formatting, but also are not focused only on general document structure as you have provided gently until now.

### What type of rule is this?

Warns about a potential problem

### Example code

Inspired by https://github.com/DavidAnson/markdownlint    I would like to see rules such as:
strong-style - Sets a consistent pattern for Strong style (** or __)
ul-style - Sets a consistent pattern for Unordered list style (* or -)
link-image-style - Sets a consistent pattern for Link and image style (inline or by reference)

Also not bad to see:
no-reversed-links - Reversed link syntax
no-trailing-punctuation - Trailing punctuation in heading
single-title/single-h1 - Multiple top-level headings in the same document
table-column-count - Table column count should equal the header count
first-line-heading/first-line-h1 - Requires First line in a file to be a top-level heading
heading-increment - Requires Heading levels to be only increment by one level at a time
no-alt-text - Images should have alternate text (alt text)
no-bare-urls - requires URLs to contain <>.
no-duplicate-heading - forbids headings with the same title/anchor.
no-empty-links - disallows to write empty URLs.
And many more that do not conflict with Prettier.

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

### Additional comments

Please consider that I am going to delete this account for reasons outside of my reach. So please keep this issue opened or absorb it under your work, because it is very appropriate for you to find valid inspiration in markdownlint, that is worth to take a look to make @eslint/markdown good enough or even better.

Also could you consider elaborating more the rules that you plan to develop for @eslint/markdown (roadmap), to let users help you to develop them and also >>to let users decide if are ever going to replace remark-lint or markdownlint in favor of @eslint/markdown, or not.

PS: https://github.com/theoludwig/markdownlint-rule-relative-links is the only plugin that I find relevant, that should have been written as a markdownlint core rule. Please consider it when planning your new rules.

**Comment by nzakas** [comment]
It seems like you haven't reviewed the available rules in this plugin, as many of the ones you mentioned already exist. We are purposely not implementing rules that can be handled by Prettier.

I'm not sure what the "delete account" thing means, but if you want to open an issue for a specific rule that doesn't already exist, please do so.
